server {
   listen       80;
   server_name  example.local;

   access_log   /var/log/nginx/example.local-acess.log;
   error_log    /var/log/nginx/example.local-error.log;

   # Если запрос заканчивается на .jpg, Nginx забирает его сам из /var/www/
   location ~* \.jpg$ {
                root /var/www;
   }

   # Все остальные запросы идут в HAProxy
   location / {
                proxy_pass      http://localhost:1325;
   }
}
